version: "2"
services:
  tacos:
    image: ctxd/circle_raspi4:latest
    container_name: 'tacos'
    tty: true
    volumes:
      - tacos-sync:/app:nocopy # nocopy is important

volumes:
  tacos-sync:
    external: true