version: "2"
services:
  tacos:
    image: ctxd/tacos:latest
    container_name: 'tacos'
    tty: true
    volumes:
      - tacos-sync:/app:nocopy # nocopy is important
  sbt:
    image: hseeberger/scala-sbt:8u222_1.3.3_2.13.1
    container_name: 'tacos_sbt'
    tty: true
    volumes:
      - ./ScheduleGenerator:/generator
      - ./src/kernel:/src/kernel
  doc:
    image: hrektts/doxygen:latest
    container_name: 'tacos_doxygen'
    tty: true
    volumes:
      - .:/data

volumes:
  tacos-sync:
    external: true
