version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Installing GCC
          command: "apt-get update && apt-get install -y gcc g++"
      - run:
          name: Install CMAKE
          command: "apt-get update && apt-get install -y cmake"
      - run:
          name: Install catch2
          command: "apt-get update && apt-get install -y catch2"
      - run:
          name: Run tests
          command: "cd test && cmake . && make && make test"
