version: "2"
services:
  tacos:
    image: ctxd/circle_raspi4:latest
    container_name: 'tacos'
    tty: true
    volumes:
      - tacos-sync:/app:nocopy # nocopy is important
  doc:
    image: hrektts/doxygen:latest
    container_name: 'tacos_doxygen'
    tty: true
    volumes:
      - .:/data

volumes:
  tacos-sync:
    external: true