name: C/C++ CI

on:
  push:
    branches: 
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/docker_make
    - name: make_project
      run: make clean && make
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
