name: C/C++ CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Project Build
    steps:
      - uses: actions/checkout@v1
      - name: Download Docker Image
        id: builder
        uses: ./.github/actions/docker_make

      - name: Where are we?
        run: ls -a

      - name: Docker Run
        run: docker run --name tacos --volume .:/app -d ctxd/tacos:path-fix

      - name: Docker Check
        run: docker ps -a

      - name: Clean
        run: docker exec --workdir /app/src/kernel tacos make clean

      - name: Second step
        run: echo 'Second Step Output'
