name: C/C++ CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Project Build
    steps:
      - name: Build Greeting Step
        id: builder
        uses: actions/docker_make@v1
        with:
          who-to-greet: "Example Argument"

      - name: Second step
        run: echo 'Second Step Output'
