name: C/C++ CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Project Build
    steps:
      - uses: actions/checkout@v1
      - name: Download Docker Image
        id: builder
        uses: ./.github/actions/docker_make

      - name: compose
        run: docker-compose up -d

      - name: Docker Check
        run: docker ps -a

      - name: Clean
        run: docker exec -i tacos make -C /app/src/kernel clean
