name: C/C++ CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Project Build
    steps:
      - uses: actions/checkout@v1
      - name: Build Greeting Step
        id: builder
        uses: ./.github/actions/docker_make

      - name: Docker Run
        run: docker run ctxd/tacos:path-fix

      - name: Docker Check
        run: docker ps -a

      - name: Second step
        run: echo 'Second Step Output'
